### ISSUE TITLE
Missing property "replicas".yaml-schema: RKE Cluster Configuration YAML Schema

### ISSUE THREAD

**Issue by XDavidT** [dcermak/vscode-rke-cluster-config#260]
The schema isn't updated and returning some errors:
https://i.imgur.com/GSCxpSC.png
https://i.imgur.com/kNzV4V1.png
https://i.imgur.com/1c65KC9.png

Before that I have only:
```
cluster_name: cnvrg
kubernetes_version: "v1.24.4-rancher1-1"
upgrade_strategy:
  max_unavailable_worker: 10%
  max_unavailable_controlplane: 1
nodes: [Here is a list of my nodes]
```
